<h2>Activation Functions</h2>

In [ ]:
import torch.nn as nn
import torch as torch

In [ ]:
x = torch.tensor([-5.0,-4.2,0.0,1.2,2.4])
print(x)

tensor([-5.0000, -4.2000,  0.0000,  1.2000,  2.4000])


In [ ]:
out = torch.relu(x)
print(out)

tensor([0.0000, 0.0000, 0.0000, 1.2000, 2.4000])


In [ ]:
#dead neuron fixing via leakyrelu
import torch.nn as nn
y = torch.tensor([-5.0,-4.2,-0.0,-1.2,-2.4])

leakyrelu = nn.LeakyReLU
out = leakyrelu(y)
print(out)

LeakyReLU(negative_slope=tensor([-5.0000, -4.2000, -0.0000, -1.2000, -2.4000]))


In [ ]:
#using sigmoid function for logistic purpose 'S curve'
sigmoid = nn.Sigmoid()
out = sigmoid(x)
print(out)

tensor([0.5000, 0.5000, 0.5000, 0.7685, 0.9168])


In [5]:
import torch.nn as nn
import torch as torch

#sigmoid for binary classification
class binary(nn.Module):
    def __init__(self):
      super().__init__()
      self.layer1=nn.Linear(4,8)
      self.layer2=nn.Linear(8,1)


    def forward(self, x):
        x = torch.relu(self.layer1(x))
        x = self.layer2(x)
        return torch.sigmoid(x)


model = binary()
x = torch.randn(5,4)
out = model(x)
print(out.shape)
print(out)

torch.Size([5, 1])
tensor([[0.5802],
        [0.5835],
        [0.5839],
        [0.5993],
        [0.5866]], grad_fn=<SigmoidBackward0>)


In [8]:
#softmax fuction for multiclass probablity
import torch
logits = torch.tensor([[5.0,4.2,0.0],[1.2,2.4,2.8]])
probs = torch.softmax(logits, dim=-1)
print(probs)

tensor([[0.6868, 0.3086, 0.0046],
        [0.1078, 0.3580, 0.5341]])


In [15]:
import torch.nn as nn
import torch

class probablity(nn.Module):
  def __init__(self):
    super().__init__()
    self.layer1=nn.Linear(5,4)
    self.layer2=nn.Linear(4,3)

  def forward(self, x):
    x = torch.relu(self.layer1(x))
    x = self.layer2(x)
    return torch.softmax(x, dim=-1)

model=probablity()
z=torch.randn(3,5)
output= model(z)
print(output.shape)
print(output)


torch.Size([3, 3])
tensor([[0.2858, 0.3881, 0.3261],
        [0.0843, 0.2152, 0.7004],
        [0.2279, 0.4304, 0.3417]], grad_fn=<SoftmaxBackward0>)
